@baseURL=http://localhost:3000/tasks
@token=tell_me_lies_tell_me_sweet_little_lies


### List all tasks
GET {{baseURL}}
Authorization: Bearer {{token}}

### Get task by id
GET {{baseURL}}/3
Authorization: Bearer {{token}}

### Create Task
POST {{baseURL}}
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"task": {
		"name": "test task",
		"description": "liar_liar_pants_on_fire"
	}
}

### Update Task
PUT {{baseURL}}/20
Authorization: Bearer {{token}}
Content-Type: application/json

{
	"task": {
		"name": "test task # 2"
	}
}

### Delete Task
DELETE {{baseURL}}/16
Authorization: Bearer {{token}}